config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :restaurants, only: %i[index new show create] do
    resources :reviews, only: %i[create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true
  validates :category, inclusion: { in: %w[chinese italian japanese french belgian] }
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :rating, presence: true
  validates :content, presence: true
  validates :rating, numericality: { only_integer: true }
  validates :rating, comparison: { greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[show]

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def show
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: %i[new create]

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render "restaurants/show", status: :unprocessable_entity
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
  <nav class="d-flex justify-content-between align-items-center p-3">
  <%= link_to "Yelp", restaurants_path, class: "btn btn-warning btn-lg text-white" %>
  <%= link_to "Add a new restaurant", new_restaurant_path, class: "btn btn-primary" %>
  </nav>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>
  <% @restaurants.each do |resto| %>
<div class="card m-3 p-3">
  <h3><%= resto.name %></h3>
  <p><%= resto.address %></p>
  <p class="badge text-black text-start m-0"><%= resto.category %></p>
  <%= link_to "More infos", restaurant_path(resto) %>
</div>
<% end %>

app/views/restaurants/new.html.erb
<h1>New restaurant</h1>
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category, collection: %w[chinese italian japanese french belgian] %>
  <%= f.submit "Submit restaurant", class: "btn btn-dark" %>
<% end %>

app/views/restaurants/show.html.erb
<div class="card m-3 p-3">
  <h1><%= @restaurant.name %></h1>
  <p><%= @restaurant.address %></p>
  <p class="badge text-black text-start m-0"><%= @restaurant.phone_number %></p>
  <p class="badge text-black text-start m-0"><%= @restaurant.category %></p>
</div>
<div class="card m-3 p-3 d-flex flex-row">
  <div class="container">
    <h2>Latest reviews</h2>
    <% @restaurant.reviews.each do |review| %>
    <div class="card m-3 p-3">
      <h5><%= review.rating %>/5</h5>
      <p><%= review.content %></p>
    </div>
    <% end %>
  </div>
  <div class="card m-3 p-3">
    <h5>Share your review</h5>
    <%= simple_form_for([@restaurant,@review]) do |f| %>
    <%= f.input :content %>
    <%= f.input :rating %>
    <%= f.submit "Submit review", class: "btn btn-dark" %>
  <% end %>
  </div>
</div>

app/views/reviews/new.html.erb
<h1>New review for <%= @restaurant.name %> </h1>
<%= simple_form_for([@restaurant,@review]) do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "Submit review", class: "btn btn-dark" %>
<% end %>